Python is dynamically-typed: variable names can point to objects of any type.

This happens as variables are in fact pointers to objects. While objects have a specific type, variables can point to objects of any type. Below, we create a variable <code>x</code> and assign it (i.e., make it point) to an integer object with value 10. After that, we re-assign variable <code>x</code> so that it points to a string object.

In [ ]:
x = 10
x = 'hello'
x = "hello to show no differences between quote and double quote"

**Q1 : Can you concatenate the strings <code>a</code>, <code>b</code> and <code>c</code>?**

In [7]:
a = "Name name is"
b = " R2D2"
c = "."

In [8]:
#Solution to Q1
a + b + c

'Name name is R2D2.'

**Q2: Can you generete a string equal to x but with all characters in upper case?**

*Remember how to use Tab to auto-complete and check methods available to strings with x.*

In [11]:
# Solution to Q2
x.upper()

NameError: name 'x' is not defined

**Q3: Can you split string x given words separated by spaces?**

In [12]:
# Solution to Q3
x= "hello to show no differences between quote and double quote"

**Q4: Can you repeat string <code>b</code> 10 times using a maximum of 3 characters?**

In [ ]:
# Solution to Q5
b = 'CMP7005'
result= b * 10
print

<h1><center> Part I: Lists </center></h1>

In [17]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits[4]

'kiwi'

In [18]:
fruits[2:5]

['pear', 'banana', 'kiwi']

In [19]:
fruits.count('apple')

2

In [20]:
fruits.index('banana')

3

In [21]:
'apple' in fruits

True

In [22]:
fruits.sort()
fruits

['apple', 'apple', 'banana', 'banana', 'kiwi', 'orange', 'pear']

In [16]:
len(fruits)

7

In [23]:
fruits += [100]
fruits

['apple', 'apple', 'banana', 'banana', 'kiwi', 'orange', 'pear', 100]

**Q1: Can you work out how to insert a new object ('strawberry') in the below defined position in the list?**

In [27]:
# Solution to Q1
fruits.insert(3, 'strawberry')
fruits

['apple',
 'apple',
 'banana',
 'strawberry',
 'strawberry',
 'strawberry',
 'strawberry',
 'banana',
 'kiwi',
 'orange',
 'pear',
 100]

**Q2: Indexing: Can you write code to select elements of x from the 3rd to the second-last element (inclusive)?**

In [31]:
# Solution to Q2:
x = [1, 2, 3, 4, 5, 6, 7, 8] # say x is the given list


**Q3: Indexing: Can you write code to select elements of x in even positions (0, 2, 4, 6 ...)?**

In [32]:
# Solution to Q3:
x = [1, 2, 3, 4, 5, 6, 7, 8] # say x is the given list
x[::2]

[1, 3, 5, 7]

In [33]:
x[1:9:2] # finding even numbers in the list

[2, 4, 6, 8]

**Q4: Indexing: Can you write code to select elements of x in odd positions (1, 3, 5...) in reverse order?**

In [34]:
# Solution to Q4:
x = [1, 2, 3, 4, 5, 6, 7, 8] # say x is the given list
x[-1:-8:-2]

[8, 6, 4, 2]

In [35]:
x[-2:-9:-2] # finding the odd numbers in the list

[7, 5, 3, 1]

**Q5: Write code that prints 'a not contained in x' if <code>a</code> is not contained in <code>x</code>.**

In [ ]:
#Given the following list
x = [1, 2, 3, 4, 5, 6, 7, 8]
a = 6.2

In [37]:
# Solution to Q5:
if a not in x
print (x)


SyntaxError: expected ':' (<ipython-input-37-240d42de1754>, line 2)

<h2><center> Tuple </center></h2>

Ordered and **immutable** collection. Values within (square brackets) and comma-separated.

In [ ]:
t = (1,2,3)
t[2] = 5

TypeError: 'tuple' object does not support item assignment

**Q1: The previous cell should generate a TypeError. Can you explain why? Can you create a list with the same values as <code>t</code> and assign 5 to position 2 of the newly created list?**

In [38]:
#Soluton to Q8:

# Error as t is a Tuple and Tuples are immutable
# A tuple offers a guarantee that a particular collection of objects will remain fixed

l = list(t)
l[2] = 5
l

NameError: name 't' is not defined

<h2><center> Dictionaries </center></h2>

Dictionaries play a key role in Python and (as we will see in future labs) in Pandas.

Dictionaries are **mappings between key and values**.

In [39]:
tel = {'jack': 4098, 'mary': 4139}
tel['guido'] = 4127
tel

{'jack': 4098, 'mary': 4139, 'guido': 4127}

In [40]:
tel['jack']

4098

In [41]:
tel.keys()

dict_keys(['jack', 'mary', 'guido'])

In [42]:
'guido' in tel
True

True

<h2><center>Sets</center></h2>

**Unordered** collections of **unique** items. Values within {curly brackets} and comma-separated. You can apply well-known set functions: union, intersection...

In [43]:
primes = {2, 3, 5, 7}
odds = set(range(1,10,2))
odds

{1, 3, 5, 7, 9}

In [47]:
primes | odds

{1, 2, 3, 5, 7, 9}

In [45]:
primes & odds

{3, 5, 7}

In [46]:
odds - primes

{1, 9}

**Q1: Can you write 1-line of code to count the number of integers from 0 to 10 that are prime and even?**

In [ ]:
# Solution Q1:
(set(range(10)))

<h2><center> Arrays </center></h2>

In [55]:
# Create a NumPy array from a Python list:
import numpy as np
list_of_numbers = [10,11,12,13,14,15,16,17,18]
numpy_array_of_numbers = np.array ( list_of_numbers)
print('\n the array from list is :',numpy_array_of_numbers)


 the array from list is : [10 11 12 13 14 15 16 17 18]


In [57]:
# Create a NumPy array with the NumPy method np.arange between 10-19
another_numpy_array = np.arange(10,19)
another_numpy_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [58]:
print(numpy_array_of_numbers.shape,another_numpy_array.shape)

(9,) (9,)


**Q1: Can you make a numpy array of only even numbers between 10 and 20 (inclusive), without using a loop?**

In [ ]:
# Solution to Q1


array([10, 12, 14, 16, 18, 20])

<h2><center> Indexing and slicing </center></h2>

In [59]:
yet_another_numpy_array = np.array([20,21,22,23,24,25,26,27,28,29])
yet_another_numpy_array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
yet_another_numpy_array[5]

25

In [61]:
yet_another_numpy_array[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [62]:
yet_another_numpy_array[:-2]

array([20, 21, 22, 23, 24, 25, 26, 27])

In [63]:
yet_another_numpy_array[[True,True,True,True,False,False,False,False,False,False]] #boolean array as mask

array([20, 21, 22, 23])

In [65]:
yet_another_numpy_array[yet_another_numpy_array > 24] #boolean array as mask

array([25, 26, 27, 28, 29])

In [66]:
yet_another_numpy_array[[0,4,5]] #fancy indexing

array([20, 24, 25])

**Q2: How would you select only values between the "4th from last" to the "2nd from last" entries of this array?**

In [ ]:
#Solution to Q2



array([26, 27])

In [67]:
array1 = np.array([[["John", "Ron", "Sean"],
                  ["Margaret", "Rachel", "Jim"],
                  ["Angel", "Joey", "Tom"]],

                 [["Max", "Maxine", "Richard"],
                  ["Barton ", "Flynn", "Simon"],
                  ["Bob", "Leo", "Kimn"]],

                 [["Wayne", "Sarah", "Lucy"],
                  ["Lucy", "Kurtis", "Yu"],
                  ["Jack", "Lex", "Alex"]]])
print(array1)

[[['John' 'Ron' 'Sean']
  ['Margaret' 'Rachel' 'Jim']
  ['Angel' 'Joey' 'Tom']]

 [['Max' 'Maxine' 'Richard']
  ['Barton ' 'Flynn' 'Simon']
  ['Bob' 'Leo' 'Kimn']]

 [['Wayne' 'Sarah' 'Lucy']
  ['Lucy' 'Kurtis' 'Yu']
  ['Jack' 'Lex' 'Alex']]]


In [68]:
array1.shape

(3, 3, 3)

In [69]:
array1.size

27

**General Access Syntax:** array1[block_index][row_index][column_index]


In [ ]:
array1 = np.array([[["John", "Ron", "Sean"],
                  ["Margaret", "Rachel", "Jim"],
                  ["Angel", "Joey", "Tom"]],

                 [["Max", "Maxine", "Richard"],
                  ["Barton ", "Flynn", "Simon"],
                  ["Bob", "Leo", "Kimn"]],

                 [["Wayne", "Sarah", "Lucy"],
                  ["Lucy", "Kurtis", "Yu"],
                  ["Jack", "Lex", "Alex"]]])
print(array1)

[[['John' 'Ron' 'Sean']
  ['Margaret' 'Rachel' 'Jim']
  ['Angel' 'Joey' 'Tom']]

 [['Max' 'Maxine' 'Richard']
  ['Barton ' 'Flynn' 'Simon']
  ['Bob' 'Leo' 'Kimn']]

 [['Wayne' 'Sarah' 'Lucy']
  ['Lucy' 'Kurtis' 'Yu']
  ['Jack' 'Lex' 'Alex']]]


In [ ]:
array1.shape

In [ ]:
array1.size

**Accessing Individual element**

In [ ]:
# First element of the first block
print(array1[0][0][0])

# Middle element of the second row in the second block
print(array1[1][1][1])

#Last element of the last block
print(array1[2][2][2])


**Accessing Entire Rows**

In [70]:
# Entire first row of the first block
print(array1[0][0])

# Entire second row of the third block
print(array1[2][1])

['John' 'Ron' 'Sean']
['Lucy' 'Kurtis' 'Yu']


**Accessing Entire Blocks**

In [71]:
#Entire third block:
print(array1 [2])
print(array1[0])


[['Wayne' 'Sarah' 'Lucy']
 ['Lucy' 'Kurtis' 'Yu']
 ['Jack' 'Lex' 'Alex']]
[['John' 'Ron' 'Sean']
 ['Margaret' 'Rachel' 'Jim']
 ['Angel' 'Joey' 'Tom']]


**Slicing the Array**

In [72]:
#Access the first column of each row from the third block:
array1[2, :, 0]

array(['Wayne', 'Lucy', 'Jack'], dtype='<U8')

In [73]:
# Access all names from the second column of each row across all blocks:
array1[:, :, 1]

array([['Ron', 'Rachel', 'Joey'],
       ['Maxine', 'Flynn', 'Leo'],
       ['Sarah', 'Kurtis', 'Lex']], dtype='<U8')

**Fancy Indexing:**

In [74]:
#You can also access specific elements from different locations using a list of indices.
array1[[0, 1], [0, 1], [0, 1]]

array(['John', 'Flynn'], dtype='<U8')

**Q3: How would you select only values of the last row starting from Wayne up to Alez?**

In [ ]:
#Solution to Q3


['Barton ' 'Flynn' 'Simon']


**Q4: How would you select Middle column, all rows, but don't flatten; keep matrix shape**

In [75]:
#Solution to Q4
# When a list is used for choosing the column, the dimension is kept


### switch the [row,column]

In [76]:
a_numpy_2d_array = np.array([[11,12],[13,14]])
a_numpy_2d_array

array([[11, 12],
       [13, 14]])

In [77]:
a_numpy_2d_array[:,0]

array([11, 13])

**Q5: Can you switch the [row,column] indices on this array?**

In [78]:
#Solution to Q5


<h2><center> Reshaping Arrays </center></h2>

In [ ]:
numpy_digits_array = np.arange(0,9)
print(numpy_digits_array, " Shape: ", numpy_digits_array.shape)

[0 1 2 3 4 5 6 7 8]  Shape:  (9,)


In [ ]:
numpy_digits_array_2D = numpy_digits_array.reshape([3,3])
print(numpy_digits_array_2D, " Shape: ", numpy_digits_array_2D.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]  Shape:  (3, 3)


In [ ]:
numpy_digits_array_2D_back_to_1D = numpy_digits_array_2D.reshape(-1)
print(numpy_digits_array_2D_back_to_1D, " Shape: ", numpy_digits_array_2D_back_to_1D.shape)

[0 1 2 3 4 5 6 7 8]  Shape:  (9,)


<h2><center> Arithmetic </center></h2>

In [ ]:
a = np.array([[10,11],[12,13]])
b = np.array([[1,-1],[-1,1]])
print("a:\n", a)
print("b:\n", b)

a:
 [[10 11]
 [12 13]]
b:
 [[ 1 -1]
 [-1  1]]


In [ ]:
print("a*b:\n", a*b)
print("a+b:\n", a+b)

In [ ]:
print("Matrix multiplication of a and b:\n",np.matmul(a,b))

In [ ]:
np.sum(a)

46

In [ ]:
print(a)
print("Sum all entries: ", np.sum(a))
print("Sum along lines: ", np.sum(a, axis=1))
print("Sum along columns: ", np.sum(a, axis=0))

#axis: the dimension of the array that will be colapsed

**Q7: Axis are important: Can you get the maximum over columns of these matrices? And the minimum over lines?**

In [ ]:
import numpy as np
a_numpy_2d_array = np.array([[11,12],[13,14]])
a_numpy_2d_array

array([[11, 12],
       [13, 14]])

In [ ]:
# Solution to Q7



Max along lines:  [11 13]
Min along columns:  [10 11]


<h1><center> Broadcasting </center></h1>

In [79]:
a = np.array([2.0, 4.0, 6.0])
b = np.array([7.0, 8.0, 9.0, 10.0])
print(a,"  ",b)

[2. 4. 6.]    [ 7.  8.  9. 10.]


In [80]:
a+b

# Error? Understand why...

ValueError: operands could not be broadcast together with shapes (3,) (4,) 